import type { Options, ParentContext } from "./index";

/**
 * Log of visited parents generated by `deepIterate`.
 *
 * A parent is an object that may contain child values/entries and is tracked during traversal.
 *
 * Only parent objects with an undefined or positive-integer child count are logged.
 *
 * @remarks
 * - Its type varies depending on the value of `visitLogType` in the {@linkcode Options options}.
 * - If it is `"null"`, there is no visit log.
 * - Use Set/WeakSet when you only need membership,
 * Map/WeakMap when you need the history per object,
 * and Array when you need the full ordered traversal history.
 *
 * Format in each structure:
 *
 * **{@link VisitLogMap Map and WeakMap}**:
 * - Key: parent object.
 * - Value: its context history.
 *
 * **{@link VisitLogArray Array}**:
 * - Value: the context for each parent.
 *
 * **{@link VisitLogSet Set and WeakSet}**:
 * - Value: the parent object.
 *
 * @since 3.0.0-beta.0
 */
export type VisitLog<P extends object, K = unknown> =
    VisitLogMap<P, K> | VisitLogSet<P> | VisitLogArray<P, K>;

/**
 * Visit log as a Map or a WeakMap.
 *
 * For each parent, the object is used as the key and its context history as the value.
 *
 * This is best when you need the ordered history of all the contexts associated with each parent.
 *
 * @since 3.0.0-beta.0
 */
export type VisitLogMap<P extends object, K = unknown> =
    Map<P, ParentContext<P, K>[]> | WeakMap<P, ParentContext<P, K>[]>;

/**
 * Visit log as a Set or a WeakSet of parent objects.
 *
 * This is best for simply knowing which objects were visited.
 *
 * @since 3.0.0-beta.0
 */
export type VisitLogSet<P extends object> = Set<P> | WeakSet<P>;

/**
 * Visit log as an array of parent contexts.
 *
 * Context objects are added in the order in which the parent objects are visited.
 *
 * This is best for getting the complete ordered history of the traversal.
 *
 * @since 3.0.0-beta.0
 */
export type VisitLogArray<P extends object, K = unknown> = ParentContext<P, K>[];
